### PR TITLE
 [JENKINS-49337] GeneralNonBlockingStepExecution

### PR DESCRIPTION
**Pull request by jglick**
Utility to solve issues like [JENKINS-49337](https://issues.jenkins-ci.org/browse/JENKINS-49337).
- [x] local test coverage
- [X] example in `withCredentials` (when using file-based credentials that could potentially block in Remoting while setting up or tearing down): https://github.com/jenkinsci/credentials-binding-plugin/pull/53
- [X] example in `withMaven` (original motivation): https://github.com/jenkinsci/pipeline-maven-plugin/pull/199
- [X] example in `wrap` (actually much older): https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/78
- [X] example in `withDockerRegistry` / `withDockerServer`: https://github.com/jenkinsci/docker-workflow-plugin/pull/158
- [x] `CpsFlowExecution.blocksRestart` integration in https://github.com/jenkinsci/workflow-cps-plugin/pull/268

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
FYI https://github.com/jenkinsci/pipeline-maven-plugin/tree/JENKINS-49337 , tests in progress

**Comment by cyrille-leclerc** [comment]
I tested tried to make pipeline-maven-plugin's `WithMavenStepExecution` extend `GeneralNonBlockingStepExecution`, I don't get regressions but `GeneralNonBlockingStepExecution` doesn't solve the `InterruptedException` after 5 mins

`WithMavenStepExecution` 's code extending `GeneralNonBlockingStepExecution` : 
https://github.com/jenkinsci/pipeline-maven-plugin/pull/190

StackTrace:

```
ERROR: [withMaven] Processing of Maven build outputs interrupted in com.cloudbees.jenkinsci.plugins.pipeline.maven.publishers.SleepMavenPublisher[disabled=false] after 299997ms.
ERROR: [withMaven] Processing of Maven build outputs interrupted after 299997ms.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.cloudbees.jenkinsci.plugins.pipeline.maven.publishers.SleepMavenPublisher.process(SleepMavenPublisher.java:34)
	at org.jenkinsci.plugins.pipeline.maven.MavenSpyLogProcessor.processMavenSpyLogs(MavenSpyLogProcessor.java:125)
	at org.jenkinsci.plugins.pipeline.maven.WithMavenStepExecution$WithMavenStepExecutionCallBack.finished(WithMavenStepExecution.java:1074)
	at org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback$TailCall.onFailure(BodyExecutionCallback.java:124)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:349)
	at com.cloudbees.groovy.cps.impl.ThrowBlock$1.receive(ThrowBlock.java:68)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$101(SandboxContinuable.java:34)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.lambda$run0$0(SandboxContinuable.java:59)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:58)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:182)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:332)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[withMaven] Publishers: Pipeline Graph Publisher: 2400 ms, Generated Artifacts Publisher: 4 ms, Invoker Publisher: 1 ms, Junit Publisher: 1 ms, Dependencies Fingerprint Publisher: 1415 ms, Findbugs Publisher: 2 ms, JGiven Publisher: 2 ms, Jacoco Publisher: 3 ms, Open Task Scanner Publisher: 2 ms, Sleep Publisher: 295737 ms
```

**Comment by jglick** [comment]
```
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.cloudbees.jenkinsci.plugins.pipeline.maven.publishers.SleepMavenPublisher.process(SleepMavenPublisher.java:34)
	at org.jenkinsci.plugins.pipeline.maven.MavenSpyLogProcessor.processMavenSpyLogs(MavenSpyLogProcessor.java:125)
	at org.jenkinsci.plugins.pipeline.maven.WithMavenStepExecution$WithMavenStepExecutionCallBack.finished(WithMavenStepExecution.java:1074)
	at org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback$TailCall.onFailure(BodyExecutionCallback.java:124)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:349)
	at …
```

https://github.com/jenkinsci/pipeline-maven-plugin/pull/190#pullrequestreview-182280588

**Comment by cyrille-leclerc** [comment]
`GeneralNonBlockingStepExecution` successfully tested on pipeline-maven-plugin solving InterruptedExecutionException! 

See https://github.com/jenkinsci/pipeline-maven-plugin/pull/190

**Comment by jglick** [comment]
> Click on the Jenkins' "stop build" and "forcibly terminate running steps" are ignored

https://github.com/jenkinsci/pipeline-maven-plugin/pull/193#discussion_r241886649

**Comment by jglick** [comment]
Channel closed on CI, sigh.

**Comment by jglick** [comment]
[Huh?](https://ci.jenkins.io/job/Plugins/job/workflow-step-api-plugin/indexing/events)

> Checking pull request #38
> ‘Jenkinsfile’ not found
> Does not meet criteria

**Comment by jglick** [comment]
Filed [INFRA-1956](https://issues.jenkins-ci.org/browse/INFRA-1956) in the meantime.

**Comment by jglick** [comment]
@cyrille-leclerc you want to prepare a PR to `pipeline-maven-plugin`? Use `2.18-rc504.616ae27933da` and link to this please for the backref.

**Pull request merged**
