### PR TITLE
[JENKINS-58716] Using gitHubRepo

### PR DESCRIPTION
**Pull request by jglick**
Example of https://github.com/jenkinsci/incrementals-tools/pull/16.

### CODE REVIEW

**Comment by jglick** [comment]
Waiting for https://repo.maven.apache.org/maven2/io/jenkins/tools/incrementals/git-changelist-maven-extension/ to have 1.2…

**Comment by jglick** [comment]
```
[INFO] Setting: -DgitHubRepo=jglick/workflow-step-api-plugin
```

Good so far…

**Comment by jglick** [comment]
Now I get a 503

```
Function host is not running.
```

:cry:

**Comment by jglick** [comment]
Now the function is running again; next problem is that it rejects my `/project/scm/url`.

**Comment by jglick** [comment]
Going to try triggering a new deployment now that https://github.com/jenkins-infra/community-functions/pull/23 is merged.

**Review by bitwiseman — APPROVED** [review]

**Pull request merged**
